/**
 * @fileoverview gRPC-Web generated client stub for app
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v4.24.4
// source: protobuf/app.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.app = require('./app_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.app.MetaClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.app.MetaPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.app.EchoRequest,
 *   !proto.app.EchoResponse>}
 */
const methodDescriptor_Meta_Echo = new grpc.web.MethodDescriptor(
  '/app.Meta/Echo',
  grpc.web.MethodType.UNARY,
  proto.app.EchoRequest,
  proto.app.EchoResponse,
  /**
   * @param {!proto.app.EchoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.app.EchoResponse.deserializeBinary
);


/**
 * @param {!proto.app.EchoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.app.EchoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.app.EchoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.app.MetaClient.prototype.echo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/app.Meta/Echo',
      request,
      metadata || {},
      methodDescriptor_Meta_Echo,
      callback);
};


/**
 * @param {!proto.app.EchoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.app.EchoResponse>}
 *     Promise that resolves to the response
 */
proto.app.MetaPromiseClient.prototype.echo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/app.Meta/Echo',
      request,
      metadata || {},
      methodDescriptor_Meta_Echo);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.app.UserOperationClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.app.UserOperationPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.app.SignUpRequest,
 *   !proto.app.SignUpResponse>}
 */
const methodDescriptor_UserOperation_SignUp = new grpc.web.MethodDescriptor(
  '/app.UserOperation/SignUp',
  grpc.web.MethodType.UNARY,
  proto.app.SignUpRequest,
  proto.app.SignUpResponse,
  /**
   * @param {!proto.app.SignUpRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.app.SignUpResponse.deserializeBinary
);


/**
 * @param {!proto.app.SignUpRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.app.SignUpResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.app.SignUpResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.app.UserOperationClient.prototype.signUp =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/app.UserOperation/SignUp',
      request,
      metadata || {},
      methodDescriptor_UserOperation_SignUp,
      callback);
};


/**
 * @param {!proto.app.SignUpRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.app.SignUpResponse>}
 *     Promise that resolves to the response
 */
proto.app.UserOperationPromiseClient.prototype.signUp =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/app.UserOperation/SignUp',
      request,
      metadata || {},
      methodDescriptor_UserOperation_SignUp);
};


module.exports = proto.app;

